### ISSUE TITLE
프로젝트 관심사별 디렉토리 및 파일 명칭 리팩토링

### ISSUE THREAD

**Issue by raeyoung** [Team-Rocket-TR/iBanner#102]
파일이 여러 개로 늘어나다보니 통일되지 않거나 구분하기 힘든 파일명이 있으니 
파일명만 봐도 알아볼 수 있도록 파일이름 수정 필요!

**Comment by raeyoung** [comment]
캔버스 레이어별 이름, 상태구분 이름을 어떻게 할지 각자 생각해봅시다

**Comment by TaeWoongKim2** [comment]
## 레이어별 명칭 정하기.

아래와 같이 생각해봤습니다.

- `RootLayer(=BackgroundLayer)`: 가장 밑에 존재하는 레이어로 'Root'라는 명칭을 사용했으나, Background도 어울릴 듯 합니다. 캔버스 배경색 및 기타 배경 베이스 관련 제어를 할 수 있는 영역입니다.

- `ImageLayer` : 이미지 레이어. 사용자가 업로드한 이미지가 그려지는 층으로 업로드된 이미지를 제어할 수 있는 영역입니다.

- `FilterLayer`   : 필터 레이어. 배경색은 아니지만 이미지와 텍스트 사이의 무엇가의 효과를 집어넣을 수 있는 영역입니다.

- `TextLayer`    :  텍스트 레이어. 글자(들)을 쓰고, 수정하고, 제어할 수 있는 영역입니다.

![image](https://user-images.githubusercontent.com/37302935/128679262-b9aebaa9-7461-4f5f-95f9-f22d0a8913d8.png)

**Comment by raeyoung** [comment]
가장 밑에 존재하는 레이어는 RootLayer 가 더 잘어울리는 것 같습니다. 
레이어 명칭 이외에도 메뉴 명칭(기본설정, 배경화면 등)도 수정예정입니다!

**Comment by TaeWoongKim2** [comment]
디렉토리 및 `Store status values` 명칭 변경 완료.

- RootLayer
- ImageLayer
- FilterLayer
- TextLayer

**Comment by TaeWoongKim2** [comment]
리팩토링 완료!
