### ISSUE TITLE
글자 스타일 selecbox 에 해당 글꼴 적용

### ISSUE THREAD

**Issue by raeyoung** [Team-Rocket-TR/iBanner#104]
글자 스타일에서 글꼴 selecbox 클릭 시 명칭만 써있고, 실제 어떤 글꼴로 표시되는지 알 수 없습니다. 
글꼴을 클릭하여 Canvas 에 뜨기 전에 selecbox 에서도 해당 글꼴모양을 알 수 있었으면 좋겠습니다.

**Comment by TaeWoongKim2** [comment]
배너 텍스트에 대한 폰트 스타일 셀렉트 박스의 옵션별 해당 글꼴 적용했습니다.
[구현 완료]
