### ISSUE TITLE
다운로드 받을 파일 명칭 지정 필요!

### ISSUE THREAD

**Issue by TaeWoongKim2** [Team-Rocket-TR/iBanner#123]
### 다운로드 이미지 파일명 설정

현재, 확장자가 PNG인 "banner"라는 이름으로만 이미지가 다운로드 됩니다.

수정 후 또 다운로드를 받는다면, banner (1).png 로 되기 때문에 구분하기가 쉽지 않습니다.

사용자의 편의성을 위해서 다운로드 받을 파일 명칭을 지정할 수 있었으면 좋겠습니다.

**Comment by TaeWoongKim2** [comment]
iBanner와 비슷한 사이트의 헤더입니다.

아래와 비슷하게 만들어도 좋을 것 같습니다.

![K-001](https://user-images.githubusercontent.com/37302935/128680371-496c1eee-70fa-4b22-9a75-595623b30f4a.png)

**Comment by raeyoung** [comment]
필수 기능은 아님.

**Comment by raeyoung** [comment]
필수 기능은 아니었으나, 사용자 편의성을 위해 수정했습니다 :)
