### ISSUE TITLE
Logo 제작

### ISSUE THREAD

**Issue by raeyoung** [Team-Rocket-TR/iBanner#68]
사이트 명칭 정하여 로고 제작  => 의뢰서 제작 필요

**Comment by TaeWoongKim2** [comment]
어플리케이션 명 "iBanner"로 이쁜 로고 제작 부탁드립니다 : )

**Comment by TaeWoongKim2** [comment]
고마운 분께 무료 외주 진행중... (기한없음)

**Comment by TaeWoongKim2** [comment]
완료

![image](https://user-images.githubusercontent.com/37302935/126899743-3b16d1fb-d41c-4f24-840b-6fe77713249c.png)
