### ISSUE TITLE
Set min value of Width and Height

### ISSUE THREAD

**Issue by TaeWoongKim2** [Team-Rocket-TR/iBanner#77]
### 가로 세로에 대한 최소 값을 설정 필요!

- '사용자 입장에서 엄청 작은 배너를 만들 필요가 있을까'라는 의문이 듭니다.

- **최소 크기 기준은 모바일**로 잡으면 좋을 것 같습니다.

- 입력값을 모두 지웠을 때 (**NULL or 0**), 설정된 최소값이 되도록 하면 좋을 것 같습니다.

**Comment by raeyoung** [comment]
값이 null 이거나 0 일 경우에는 width 및 height 기본값을 200 px 으로 변경하겠습니다!

**Comment by raeyoung** [comment]
1. 가로 및 세로가 0일 경우 200으로 처리
2. 가로 및 세로의 길이는 4자리로 제한
