### ISSUE TITLE
어플리케이션 배포시, 후원하기 이미지 깨짐 현상

### ISSUE THREAD

**Issue by TaeWoongKim2** [Team-Rocket-TR/iBanner#82]

**Comment by TaeWoongKim2** [comment]
webpack 및 이미지를 상대경로로 수정 요청

**Comment by raeyoung** [comment]
Sponsor.jsx 에 import kakaopayQRrcode from './src/public/image/kakaopay_QRcode.png'; 로 import 하면 
에러가 나고, img 태그에 직접 입력하면 에러가 나지 않습니다.

**Comment by raeyoung** [comment]
window 에서 import kakaopayQRrcode from '/src/public/image/kakaopay_QRcode.png'; 사용시에는 에러가 나지 않습니다.

**Comment by TaeWoongKim2** [comment]
해당 버그 수정 완료한걸까요?
완료됐다면, 이슈 닫아주세요 : )

**Comment by raeyoung** [comment]
경로 수정으로 버그 수정 완료!
