### ISSUE TITLE
Request additional information about the Sponsorship menu

### ISSUE THREAD

**Issue by TaeWoongKim2** [Team-Rocket-TR/iBanner#93]
### 후원하기 메뉴에 대한 추가 정보 요청

- 현재, 후원하기는  Kakao QR code만 존재하고 있습니다.
- iBanner를 만드는데 누가기여 했는지 및 개선사항에 대한 건의 이메일 등에 대한 추가적인 정보가 있었으면 좋겠습니다.

---------------------------------
#### Contributors
> 

Kim Raeyoung & Kim Taewoong
 ( Git Link )               ( Git Link )

---------------------------------
#### Contact us
> about app improvement

e-Mail ~~~~

----------------------------------
#### Donation
> for Junior Developer

Kakao QR Code

----------------------------------

위는 '이러한 구성 요소들이 있었으면 좋겠다.' 를 표현한 것입니다.

UI적인 부분은 React Material UI 공식 페이지에서 깔끔한 UI 컴포넌트를 사용하면 될 것 같습니다.

화이링~ 👍

**Comment by raeyoung** [comment]
알겠습니다!

**Comment by TaeWoongKim2** [comment]
?

**Comment by raeyoung** [comment]
기여자, 연락하기 추가하여 완료했습니다! 
추후 필요하면 UI 수정 예정입니다 ~ :)
